export const theme = {
  colors: {
    background: '#F9F6ED',
    primary: '#34855b',
    accent: '#d07158',
    textDark: '#2f2926',
    neutralDark: '#333',
    white: '#ffffff',
    lightGray: '#E5E5EA',
    mediumGray: '#8E8E93',
    correct: '#4CAF50',
    correctBg: '#E8F5E9',
    incorrect: '#F44336',
    incorrectBg: '#FFEBEE',
  },
  fonts: {
    gothamBlack: 'Gotham-Black',
    gothamBold: 'Gotham-Bold',
    gothamMedium: 'Gotham-Medium',
    gothamBook: 'Gotham-Book',
    gothamLight: 'Gotham-Light',
    uniSansHeavy: 'UniSans-Heavy',
    uniSansThin: 'UniSans-Thin',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
};
